manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.4.2
      path: deps/zephyr
      import: true
    - name: sensor_xyz
      url: https://github.com/grmz9hhf9j-blip/fake_accel_sensor
      revision: main
      path: modules/sensor_xyz
  self:
    path: .
  